const indexdata = {
   // name: "Nike Air", 
   // navlist: "SHOP", 
   // bannerimg1: "shoe1.png", 
   // bannerimg2: "shoe2.png", 
   // bannerimg3: "shoe3.png",
   n1title: "N-Air Purple-Yellow",
   n1img: "f-l.jpg", 
   n1des: "FlyEase technology gives you the performance you’d expect, with easy access for all athletes. Just launched.",
   n2title: "N-Air Blue-Red",
   n2img: "f-r.png", 
   n2des: "The Air Max 270 in two new colourways to keep you on your toes. JUST GO BIGGER!!!",
   shoe1: "Nike Air Zoom Pegasus 35 FlyEase",
   price1: "CAD 155",
   shoeimg1: "shoe4.jpg",
   shoe2: "Nike Zoom Pegasus 34 FlyEase",
   price2: "CAD 105",
   shoeimg2: "shoe5.jpg",
   shoe3: "LeBron Soldier XII FlyEase",
   price3: "CAD 175",
   shoeimg3: "shoe6.jpg",
   shoe4: "LeBron Soldier 11 FlyEase",
   price4: "CAD 130",
   shoeimg4: "shoe7.jpg",
   shoe5: "Nike Revolution 4 FlyEase",
   price5: "CAD 82",
   shoeimg5: "shoe8.jpg",
   shoe6: "Jordan 'Why Not?' Zer0.2",
   price6: "CAD 170",
   shoeimg6: "shoe9.jpg",
   shoe7: "Nike Team Hustle D 8 FlyEase",
   price7: "CAD 75",
   shoeimg7: "shoe10.jpg",
   shoe8: "Nike Air LeBron 16 FlyEase",
   price8: "CAD 240",
   shoeimg8: "shoe11.jpg",
   shoe9: "Nike Air Max 97 FlyEase",
   price9: "CAD 215",
   shoeimg9: "shoe12.jpg",
   shoe10: "Nike Air Force 1 '07 FlyEase",
   price10: "CAD 120",
   shoeimg10: "shoe13.jpg",
   shoe11: "AIR JORDAN 5 LANEY JSP",
   price11: "CAD 265",
   shoeimg11: "shoe14.jpg",
   shoe12: "Nike Zoom Pegasus Turbo",
   price12: "CAD 240",
   shoeimg12: "shoe15.jpg",
}

module.exports = indexdata;